#!/bin/sh
set -e

confDir=/usr/local/etc/php
extDir="$(php -d 'display_errors=stderr' -r 'echo ini_get("extension_dir");')"

if [ -n "$XDEBUG_ENABLED" ]; then
    echo "zend_extension=${extDir}/xdebug.so" > ${confDir}/conf.d/docker-php-ext-xdebug.ini

    if [ "" != "$XDEBUG_REMOTE_HOST" ]; then
        sed -i "s/xdebug.remote_host=host.docker.internal/xdebug.remote_host=${XDEBUG_REMOTE_HOST}/" ${confDir}/conf.d/xdebug.ini
    fi

    if [ "" != "$XDEBUG_REMOTE_PORT" ]; then
        sed -i "s/xdebug.remote_host=48000/xdebug.remote_host=${XDEBUG_REMOTE_PORT}/" ${confDir}/conf.d/xdebug.ini
    fi

    if [ "" != "$XDEBUG_REMOTE_CONNECT_BACK" ]; then
        sed -i "s/xdebug.remote_connect_back=0/xdebug.remote_connect_back=${XDEBUG_REMOTE_CONNECT_BACK}/" ${confDir}/conf.d/xdebug.ini
    fi

    if [ "" != "$XDEBUG_IDE_KEY" ]; then
        sed -i "s/xdebug.idekey=PHPSTORM/xdebug.idekey=${XDEBUG_IDE_KEY}/" ${confDir}/conf.d/xdebug.ini
    fi

    XDEBUG_GREP_HOST=$(grep "xdebug.remote_host=" ${confDir}/conf.d/xdebug.ini | awk -F= '{ print $2 }')
    XDEBUG_GREP_PORT=$(grep "xdebug.remote_port" ${confDir}/conf.d/xdebug.ini | awk -F= '{ print $2 }')
    echo "XDebug enabled. Client - ${XDEBUG_GREP_HOST}:${XDEBUG_GREP_PORT}"
fi

if [ -n "$OPCACHE_ENABLED" ]; then
    echo "zend_extension=${extDir}/opcache.so" > ${confDir}/conf.d/docker-php-ext-opcache.ini
    echo "ZendOpcache enabled"
fi

if [ -n "$MONGODB_ENABLED" ]; then
    echo "extension=mongodb.so" > ${confDir}/conf.d/docker-php-ext-mongodb.ini
    echo "MongoDB enabled"
fi

if [ -n "$REDIS_ENABLED" ]; then
    echo "extension=redis.so" > ${confDir}/conf.d/docker-php-ext-redis.ini
    echo "Redis enabled"
fi

if [ -n "$MEMCACHED_ENABLED" ]; then
    echo "extension=memcached.so" > ${confDir}/conf.d/docker-php-ext-memcached.ini
    echo "Memcached enabled"
fi

# Setup user for linux based development
if [ "x" != "x${GID}" ]; then
    groupmod -g $GID www-data

    if [ "x" = "x${UID}" ]; then
        usermod -g $GID www-data
    fi
    echo "Updated apache2 gid www-data to ${GID}"
fi
if [ "x" != "x${UID}" ]; then
    if [ "x" != "x${GID}" ]; then
        usermod -g $GID -u $UID www-data
    else
        usermod -u $UID www-data
    fi
    echo "Updated apache2 uid www-data to ${UID}"
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
elif [ "cli" = "$1" ]; then
    shift 1
    set -- gosu www-data php "$@"
elif [ "bash" = "$1" ]; then
    shift 1
    set -- gosu www-data bash "$@"
fi

exec "$@"
