#!/bin/sh
set -e

confDir=/usr/local/etc/php
extDir="$(php -d 'display_errors=stderr' -r 'echo ini_get("extension_dir");')"

##
# Enable XDebug
# 
# Parameters:
#  1 - xdebug client host
#  2 - xdebug ide key
#
function enable_xdebug() {
    local XDEBUG_CLIENT_HOST=${1}
    local XDEBUG_IDE_KEY=${2}

    echo "zend_extension=${extDir}/xdebug.so" > ${confDir}/conf.d/docker-php-ext-xdebug.ini

    if [ "" != "$XDEBUG_CLIENT_HOST" ]; then
        sed -i "s/xdebug.client_host=host.docker.internal/xdebug.client_host=${XDEBUG_CLIENT_HOST}/" ${confDir}/conf.d/xdebug.ini
    fi

    if [ "" != "$XDEBUG_IDE_KEY" ]; then
        sed -i "s/xdebug.idekey=PHPSTORM/xdebug.idekey=${XDEBUG_IDE_KEY}/" ${confDir}/conf.d/xdebug.ini
    fi

    XDEBUG_GREP_HOST=$(grep "xdebug.client_host=" ${confDir}/conf.d/xdebug.ini | awk -F= '{ print $2 }')
    XDEBUG_GREP_PORT=$(grep "xdebug.client_port" ${confDir}/conf.d/xdebug.ini | awk -F= '{ print $2 }')
    echo "XDebug enabled. Client: ${XDEBUG_GREP_HOST}:${XDEBUG_GREP_PORT}"
}

function enable_opcache() {
    echo "zend_extension=${extDir}/opcache.so" > ${confDir}/conf.d/docker-php-ext-opcache.ini
    echo "ZendOpcache enabled"
}

function enable_mongodb() {
    echo "extension=mongodb.so" > ${confDir}/conf.d/docker-php-ext-mongodb.ini
    echo "MongoDB enabled"
}

function set_wwwdata_user() {
    local UID=${1}
    local GID=${1:-""}

    usermod -u $UID www-data

    if [ "x" != "x${GID}" ]; then
        usermod -g $GID -u $UID www-data
    fi
}
