name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  FPM_ALPINE_VERSION: fpm-alpine3.15
  PHP_VERSION: 8.1.9

jobs:
  build_php_8_1_fpm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login o DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Setup dockerx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        build-args: BASE_IMAGE=php:${{ env.PHP_VERSION }}-${{ env.FPM_ALPINE_VERSION }}
        context: ./php-8.1/${{ env.FPM_ALPINE_VERSION }}
        file: ./php-8.1/${{ env.FPM_ALPINE_VERSION }}/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php:8.1-${{ env.FPM_ALPINE_VERSION }}
