name: PHP 8.2 Alpine 3.16 CI

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FPM_ALPINE_VERSION: fpm-alpine3.16
  PHP_VERSION: 8.2

jobs:
  build_php_fpm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login o DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup dockerx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: BASE_IMAGE=php:${{ env.PHP_VERSION }}-${{ env.FPM_ALPINE_VERSION }}
        context: ./php-${{ env.PHP_VERSION }}/${{ env.FPM_ALPINE_VERSION }}
        file: ./php-${{ env.PHP_VERSION }}/${{ env.FPM_ALPINE_VERSION }}/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/php:${{ env.PHP_VERSION }}-${{ env.FPM_ALPINE_VERSION }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/php:${{ env.PHP_VERSION }}-${{ env.FPM_ALPINE_VERSION }}-bcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/php:${{ env.PHP_VERSION }}-${{ env.FPM_ALPINE_VERSION }}-bcache,mode=max
        platforms: linux/arm64,linux/amd64
